import re

import streamlit as st

_REPORT_CSS = """
<style>
.report-section {
    font-size: 0.97rem; line-height: 1.8; color: #1a1a2e;
}
.report-section h1 { color: #1a1a2e; font-size: 1.6rem; }
.report-section h2 {
    color: #2c3e50; font-size: 1.15rem; margin-top: 1.5rem;
    border-bottom: 1px solid #dee2e6; padding-bottom: 0.25rem;
}
.report-section h3 { color: #4a90d9; font-size: 1rem; }
.report-section table {
    width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.87rem;
}
.report-section th { background: #e9ecef; padding: 0.45rem 0.75rem; text-align: left; }
.report-section td { padding: 0.35rem 0.75rem; border-bottom: 1px solid #e9ecef; }
.report-section tr:hover td { background: #f1f3f5; }
</style>
"""


def render_report(load_report, user_dir, simple=False):
    """Render the report tab.

    The report markdown may contain raw-HTML blocks (for the household profile
    section) delimited by RAW_HTML_START / RAW_HTML_END comments.  We split on
    those markers and render each segment correctly:
      - Markdown segments -> st.markdown via md_lib (tables, bold, headings)
      - HTML segments     -> st.markdown(unsafe_allow_html=True) directly,
                             so <div> tags are never double-processed.
    """
    #st.header("Analysis Report")
    report_text = load_report()

    if report_text is None:
        st.warning("Report not found. Run the pipeline to generate it.")
        return

    # Strip embedded image references (figures not available in-app)
    clean = re.sub(
        r"^#{1,4} .+\n!\[.*?\]\(figures/.*?\)\n?",
        "", report_text, flags=re.MULTILINE,
    )
    clean = re.sub(
        r"^!\[.*?\]\(.*?\)\n?",
        "", clean, flags=re.MULTILINE,
    )

    st.markdown(_REPORT_CSS, unsafe_allow_html=True)

    # Split on the HTML-block sentinels written by reporting.py
    segments = re.split(
        r"(<!-- RAW_HTML_START -->.*?<!-- RAW_HTML_END -->)",
        clean,
        flags=re.DOTALL,
    )

    for seg in segments:
        seg = seg.strip()
        if not seg:
            continue

        if seg.startswith("<!-- RAW_HTML_START -->"):
            # Strip the comment markers, render the raw HTML directly
            html = re.sub(r"<!--.*?-->", "", seg, flags=re.DOTALL).strip()
            st.markdown(html, unsafe_allow_html=True)
        else:
            # Markdown segment
            try:
                import markdown as md_lib
                html_md = md_lib.markdown(seg, extensions=["tables"])
                st.markdown(
                    f'<div class="report-section">{html_md}</div>',
                    unsafe_allow_html=True,
                )
            except ImportError:
                st.markdown(seg, unsafe_allow_html=True)

    if not simple:
        _render_html_visuals(user_dir)
        _render_outlier_tables(user_dir)

    with st.expander("View raw markdown"):
        st.code(report_text, language="markdown")


def _render_html_visuals(user_dir):
    """Show any pre-generated Plotly HTML charts that exist on disk."""
    html_dir = user_dir / "html"
    existing_htmls = sorted(html_dir.glob("*.html")) if html_dir.exists() else []
    if not existing_htmls:
        return

    st.subheader("Generated Visuals")
    st.caption("Only charts that exist on your machine are shown below.")
    for html_file in existing_htmls:
        with st.expander(html_file.stem.replace("_", " ").title()):
            st.html(html_file.read_text(encoding="utf-8"))


def _render_outlier_tables(user_dir):
    """Display IQR and 3-sigma outlier CSVs if they were generated by the pipeline."""
    st.divider()
    st.subheader("Outlier Data")

    outlier_files = {
        "IQR method":    user_dir / "processed" / "outliers_iqr.csv",
        "3-sigma method": user_dir / "processed" / "outliers_3sigma.csv",
    }

    import pandas as pd
    for label, path in outlier_files.items():
        if not path.exists():
            st.caption(f"{label}: file not found (`{path.name}`).")
            continue

        df_out = pd.read_csv(path)
        drop_cols = [c for c in ["datetime", "method", "lower_limit", "upper_limit"]
                     if c in df_out.columns]
        display_df = df_out.drop(columns=drop_cols).round(4)

        with st.expander(f"{label} -- {len(df_out)} flagged readings", expanded=True):
            st.dataframe(display_df, width="stretch",
                         height=min(400, 40 + len(display_df) * 35))
